In [2]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

In [11]:
img = cv2.imread(r'D:\IPCV\LAB-EXP-8\images\2.jpg')

In [17]:
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

In [18]:
hsv = cv2.cvtColor(img,cv2.COLOR_BGR2HSV)

In [19]:
h,s,v = cv2.split(hsv)

In [21]:
print(hsv)

[[[  7 190 255]
  [  6 205 243]
  [  6 213 234]
  ...
  [ 26 206 250]
  [ 26 206 250]
  [ 26 206 250]]

 [[  6 205 246]
  [  6 209 242]
  [  6 219 231]
  ...
  [ 26 206 250]
  [ 26 206 250]
  [ 26 206 250]]

 [[  6 211 243]
  [  6 216 237]
  [  6 216 237]
  ...
  [ 26 206 250]
  [ 26 206 250]
  [ 26 206 250]]

 ...

 [[ 49  70 167]
  [ 49  64 183]
  [ 49  67 174]
  ...
  [ 55 117 126]
  [ 53 112 127]
  [ 52 119 120]]

 [[ 49  72 162]
  [ 49  66 177]
  [ 49  64 183]
  ...
  [ 55 121 122]
  [ 53 131 109]
  [ 52 112 127]]

 [[ 49  71 165]
  [ 49  68 173]
  [ 49  63 185]
  ...
  [ 55 131 113]
  [ 53 136 105]
  [ 52 139 103]]]


In [25]:
lower_h = 35
upper_h = 85

In [26]:
mask = cv2.inRange(h,lower_h,upper_h)

In [27]:
result = cv2.bitwise_and(img,img,mask=mask)

In [28]:
print(mask)

[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [30]:
cv2.imwrite('mask.jpg',result)

True

# Add Saturation and Value filtering

In [31]:
lower_green = np.array([35, 50, 50])   # H, S, V (min)
upper_green = np.array([85, 255, 255]) # H, S, V (max)

In [32]:
mask = cv2.inRange(hsv, lower_green, upper_green)

In [33]:
result = cv2.bitwise_and(img, img, mask=mask)

In [36]:
# Save original image
cv2.imwrite(r'D:\IPCV\LAB-EXP-8\original.jpg', img)

# Save HSV image (note: colors will look different if opened normally)
cv2.imwrite(r'D:\IPCV\LAB-EXP-8\hsv.jpg', hsv)

# Save individual channels
cv2.imwrite(r'D:\IPCV\LAB-EXP-8\hue.jpg', h)
cv2.imwrite(r'D:\IPCV\LAB-EXP-8\saturation.jpg', s)
cv2.imwrite(r'D:\IPCV\LAB-EXP-8\value.jpg', v)

# Save final filtered result
cv2.imwrite(r'D:\IPCV\LAB-EXP-8\filtered_green.jpg', result)

True